ALLOWED_EXTENSIONS: !!set
  xml: null
  zip: null
DEBUG: false
MAIL_ASCII_ATTACHMENTS: false
MAIL_DEBUG: false
MAIL_DEFAULT_SENDER: null
MAIL_MAX_EMAILS: null
MAIL_PASSWORD: null
MAIL_PORT: 587
MAIL_SERVER: smtp.gmail.com
MAIL_SUPPRESS_SEND: false
MAIL_USERNAME: null
MAIL_USE_SSL: false
MAIL_USE_TLS: true
OTS_AIRPLANES_LIVE_LAT: 40.744213
OTS_AIRPLANES_LIVE_LON: -73.986939
OTS_AIRPLANES_LIVE_RADIUS: 10
OTS_BACKUP_COUNT: 7
OTS_CA_CITY: YY
OTS_CA_COUNTRY: WW
OTS_CA_EXPIRATION_TIME: 3650
OTS_CA_FOLDER: /app/ots/ca
OTS_CA_NAME: OpenTAKServer-CA
OTS_CA_ORGANIZATION: ZZ
OTS_CA_ORGANIZATIONAL_UNIT: OpenTAKServer
OTS_CA_PASSWORD: atakatak
OTS_CA_STATE: XX
OTS_CA_SUBJECT: /C=WW/ST=XX/L=YY/O=ZZ/OU=OpenTAKServer
OTS_DATA_FOLDER: /app/ots
OTS_EMAIL_DOMAIN_BLACKLIST: []
OTS_EMAIL_DOMAIN_WHITELIST: []
OTS_EMAIL_TLD_BLACKLIST: []
OTS_EMAIL_TLD_WHITELIST: []
OTS_ENABLE_EMAIL: false
OTS_ENABLE_MUMBLE_AUTHENTICATION: false
OTS_ENABLE_TCP_STREAMING_PORT: true
OTS_LISTENER_ADDRESS: 127.0.0.1
OTS_LISTENER_PORT: 8081
OTS_MARTI_HTTPS_PORT: 8443
OTS_MARTI_HTTP_PORT: 8080
OTS_MEDIAMTX_API_ADDRESS: http://localhost:9997
OTS_MEDIAMTX_TOKEN: '328926193709942967845870496817739901275'
OTS_NODE_ID: ayaa7dhtna01s71sankae1jgzid1lwjgnregx8s43qhljwvihgcqhpmp3h446f44
OTS_RABBITMQ_SERVER_ADDRESS: 127.0.0.1
OTS_SSL_STREAMING_PORT: 8089
OTS_SSL_VERIFICATION_MODE: 2
OTS_TCP_STREAMING_PORT: 8088
REMEMBER_COOKIE_SAMESITE: strict
SCHEDULER_API_ENABLED: false
SECRET_KEY: ba3106150c483120008a415e7c09d94ffa811f76e40103f76e8763320ffd5c62
SECURITY_CHANGEABLE: true
SECURITY_CHANGE_URL: /password/change
SECURITY_CONFIRMABLE: false
SECURITY_CSRF_COOKIE_NAME: XSRF-TOKEN
SECURITY_CSRF_IGNORE_UNAUTH_ENDPOINTS: true
SECURITY_LOGIN_WITHOUT_CONFIRMATION: true
SECURITY_PASSWORD_LENGTH_MIN: 8
SECURITY_PASSWORD_SALT: '229930412083425196929776783858924512684'
SECURITY_POST_CONFIRM_VIEW: /login
SECURITY_RECOVERABLE: false
SECURITY_REDIRECT_BEHAVIOR: spa
SECURITY_REGISTERABLE: false
SECURITY_RESET_URL: /password/reset
SECURITY_RESET_VIEW: /reset
SECURITY_RETURN_GENERIC_RESPONSES: true
SECURITY_TOTP_ISSUER: OpenTAKServer
SECURITY_TOTP_SECRETS:
  1: O6BBOBRQWSADCUVQDHEBOIJ42H3PGT76
SECURITY_TRACKABLE: true
SECURITY_TWO_FACTOR: true
SECURITY_TWO_FACTOR_ALWAYS_VALIDATE: false
SECURITY_TWO_FACTOR_ENABLED_METHODS:
- authenticator
- email
SECURITY_TWO_FACTOR_RESCUE_MAIL: null
SECURITY_URL_PREFIX: /api
SECURITY_USERNAME_ENABLE: true
SECURITY_USERNAME_REQUIRED: true
SESSION_COOKIE_SAMESITE: strict
SQLALCHEMY_DATABASE_URI: sqlite://///app/ots/ots.db
SQLALCHEMY_ECHO: false
SQLALCHEMY_ENGINE_OPTIONS:
  pool_pre_ping: true
SQLALCHEMY_RECORD_QUERIES: false
SQLALCHEMY_TRACK_MODIFICATIONS: false
UPLOAD_FOLDER: /app/ots/uploads
WTF_CSRF_CHECK_DEFAULT: false
WTF_CSRF_TIME_LIMIT: null
